name: Lab08 CI
run-name: Lab08 CI is testing out GitHub Actions 🚀
on: [push]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-22.04
        strategy:
            fail-fast: false
            matrix:
                python-version: ["3.10"]

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  pip install angr
            - name: Verify result
              run: |
                  cd Lab08
                  bash -c "time python3 solve.py"
                  cat solve_input
                  cat solve_input | src/prog
                  python3 verify.py
